import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Arrow functions only: `const name = () => {}`, never `function name() {}`.
  {
    rules: {
      "func-style": ["error", "expression"],
      "prefer-arrow-callback": "error",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Orval from openapi.json.
    "src/lib/api/generated/**",
  ]),
]);

export default eslintConfig;
